# build stage
FROM golang:1.25.4-trixie AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build


# final stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/bin/ /bin/

EXPOSE 8080
ENV SERVER_PORT=8080
ENTRYPOINT ["/bin/shipping-optimizer"]


